services:
  app1:
    build: ./app
    container_name: app1
    environment:
      - PORT=3033
  app2:
    build: ./app
    container_name: app2
    environment:
      - PORT=3033
  app3:
    build: ./app
    container_name: app3
    environment:
      - PORT=3033
  app4:
    build: ./app
    container_name: app4
    environment:
      - PORT=3033
  app5:
    build: ./app
    container_name: app5
    environment:
      - PORT=3033
  app6:
    build: ./app
    container_name: app6
    environment:
      - PORT=3033
  app7:
    build: ./app
    container_name: app7
    environment:
      - PORT=3033
  app8:
    build: ./app
    container_name: app8
    environment:
      - PORT=3033
  app9:
    build: ./app
    container_name: app9
    environment:
      - PORT=3033

  nginx:
    image: nginx:latest
    container_name: load-balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
      - app3
      - app4
      - app5
      - app6
      - app7
      - app8
      - app9

  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:latest
  #   container_name: cadvisor1
  #   ports:
  #     - "8889:8080"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro